In [1]:
import torch
x = torch.Tensor([3,4])
y = torch.Tensor([2,7])
print(x*y)


tensor([ 6., 28.])


In [2]:
x = torch.zeros([2,5])

In [3]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [6]:
y = torch.rand(2,5)

In [7]:
y

tensor([[0.4053, 0.5276, 0.9959, 0.2288, 0.0155],
        [0.3138, 0.4054, 0.4511, 0.9356, 0.4776]])

In [8]:
y.view([1,10])

tensor([[0.4053, 0.5276, 0.9959, 0.2288, 0.0155, 0.3138, 0.4054, 0.4511, 0.9356,
         0.4776]])